index.js, test/index.test.js
This pull request turns instance_id into a derived field and makes hostname and port fields that are set by the user.
=> Changed hostname and port to be input fields and not derived

lib/model.js
connection-model was a very chatty component in terms of debug messages, but they weren't actually all that helpful.
=> remove debug logging output

lib/model.js, package.json, test/index.test.js
We don't require the user to select a local port - we select it for them. Port is actually the server SSH port, which defaults to 22.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/76)
=> INT-1408: SSH Tunnel port is remote port not local

lib/ssh-tunnel.js
Workaround a bug in `tunnel-ssh` where the error event is not handled.
This causes an UncaughtException in cases such as attempting to use a
key which is passphrase protected but not providing the passphrase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/110)
=> INT-1771: Fix UncaughtException when not providing a required passphrase

lib/model.js, test/index.test.js
Using [`ssl=prefer`](https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#connection-configuration) in the URL passed to the driver which:
> prefer: the driver tries to initiate each connection with SSL, and falls back to without SSL if it fails.
`ssl=IFAVAILABLE` also sets the driver options below to use the system certificate authority per INT-1709 :
```javascript
{
server: {
checkServerIdentity: false,
sslValidate: true
}
}
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/109)
=> INT-1709: SSL "If Available"

lib/connect.js, test/index.test.js
Originally didn’t know why keeping the options = opts line around works, but it works and is now unit tested.
Found by the magical principle of git bisect.
[Probably no longer] CAVEATS:
1. Required connection-model@{master, currently v6.3.0}, i.e. where this commit is (probably would work anywhere on the 5.x series if we want to limit the number of changes to the 1.4.x stable branch if that isn't up to date).
2. Seemed to need data-service@1.4.0, but later found that upgrading to 2.0.0 seems fine too.
3. Works on 1.3-releases branch only so far, I get an “Auth failed” on 1.4-releases, so there’s at least one more regression!
EDIT: Later tracked down the “Auth failed” error into the hadron-build dependency. This turned out to be resolvable by running the “Master is broken” instructions, …
=> COMPASS-140: Restore SSL option - server and client validation

.travis.yml, package.json
Based on https://github.com/mongodb-js/index-model/commit/19eb5ce1b6e7ae41614e302ee99a624cca9701ce
Tested with the same Ubuntu VM @ 10% CPU execution cap scenario, this reproduces the `beforeAll` timeouts on master seen in https://github.com/mongodb-js/index-model/pull/53 and resolves them after (and for good measure in my testing, reproduces the errors again if you go back to the before state, clearing out all mongodb-version-manager test cache files and `killall mongod` as well).
=> COMPASS 443: Travis errors: Add mongodb-runner pretest and sudo: required

lib/connect.js, package.json, test/connect.test.js
When `MongoClient.connect()` returns error, make sure to close the ssh tunnel if it was created.
=> COMPASS-527 close tunnel on error

test/connect.test.js
This PR aims to restore the connection model tests after we dropped connection-fixture support, and is required to unblock other PRs like COMPASS-811: https://github.com/mongodb-js/connection-model/pull/159
=> COMPASS-812: Update connection-model tests for connection-fixture changes

lib/model.js, test/index.test.js
Atlas updated their copy/paste connection string:
Hence we should support the new version in Compass.
While in the area, this also updates the default Atlas SSL option from UNVALIDATED to SYSTEMCA, so in future we won't need to override it in as many places in Compass itself.
=> COMPASS 830: Use a more general PASSWORD check for Atlas

README.md, lib/model.js, test/index.test.js
A quick fix for something that has been bugging me but is never important enough to be scheduled:
Allow passing in application name which will be passed to the server and appear in log files and profiling collections. See https://docs.mongodb.com/manual/reference/log-messages/#client-data
=> COMPASS-829 add app name property

lib/model.js, test/index.test.js
This PR adds a test and fix for `@` being double-encoded to `%2540` in mongoDB URLs which are passed along, for instance to the node driver.
BEFORE
AFTER
Note: It looks like Kerberos and X.509 are also affected by this. We don't support X.509 in Compass (yet) and will investigate Kerberos on COMPASS 851.
=> COMPASS-745 LDAP @ in username gets double encoded

README.md, lib/model.js, test/index.test.js
as part of COMPASS-1013, we need to add the ability to customize the driver options, e.g. specifying `connectTimeoutMS` and `socketTimeoutMS` for connections.
This change adds a new property `extra_options` to the model, which will be merged into the derived property `driver_options`.
See added tests for usage.
Another change: I removed the now obsolete `uri_decode_auth` option, which causes warnings in Compass. This option [was removed from the node driver](https://github.com/mongodb/node-mongodb-native/pull/1488) in version 2.2.25. It now always decodes the auth credentials.
Finally, there was also a small typo in the deps for `driver_options` which is fixed now.
=> COMPASS-1013 add extra options

lib/model.js, test/index.test.js
This PR removes `promote_values` prop from connection model. As it is no longer necessary for CRUD actions. Having this here adds `promoteValues` to the connection state which interferes with the node driver's cursor; prematurely setting `topologyOptions.promoteValues` to true [here](https://github.com/christkv/mongodb-core/blob/9cf1dd46595bcaf5b9ef5227bbdd679247def750/lib/cursor.js#L116-L120).
By the time the connection is set to data-service  (see above)  there's already a preference (i.e. favouring toplogyOptions) which overrides any direct queries sent to the node driver.
I'm not entirely sure what `topologyOptions` refers to [from the link above](https://github.com/christkv/mongodb-core/blob/9cf1dd46595bcaf5b9ef5227bbdd679247def750/lib/cursor.js#L116-L120) because it is preferred …
=> COMPASS-915: Remove Promote Values from Connection Model

lib/model.js, test/index.test.js
⚠️ This is built on top of #174 to make it easier to review. 
This PR applies the node builtin `encodeURIComponent` manually to the auth username and password sections, allowing MongoDB users in downstream applications to authenticate if their username or password contains characters such as `:` or 👌emoji😂😍😘🔥💕🎁💯🌹.
See also the upstream node issue:
nodejs/node#1802
Note: I also considered the following alternative which would be RFC3986-compliant, but found it had significantly higher latency, see:
http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#authenticate
https://tools.ietf.org/html/rfc3986#section-3.2.1
=> COMPASS-972: Cannot authenticate if username or password contains a ":" or emoji

lib/model.js, test/index.test.js
[CHARTS-306](https://jira.mongodb.org/browse/CHARTS-306) adds additional stitch related options to the connection model to support both Atlas and on-prem stitch connections.
Included here are:
- connectionType
- stitchServiceName
=> CHARTS-306: Support atlas/on-prem connections for Stitch in connection-model

README.md, constants/ssl-method-values.js, lib/extended-model.js, lib/model.js, test/build-uri.test.js, test/parse-uri-common-targets.test.js
- Variable name change to be consistent with compass connection plugin (sslType was replaced with sslMethod)
- Extended model was updated to ensure we create our a subclass or we won't have the storage mixin available
=> COMPASS-3607 Consistency with compass connection

README.md, lib/model.js, package-lock.json, package.json, test/parse-uri-components.test.js
Ability to test SRV connection strings.
Driver parser resolves the SRV record and uses the result as the list of hosts to connect to. Since tests don't have real data that can be resolved the driver check always fails. To make tests work we need to mock `dns.resolveSrv()` and `dns.resolveTxt()` methods. To do so the `proxyquire` module was added to the project. It has an ability to replace a particular module through making this module kind of global `'@global': true`. By doing this a module can be overwritten in the test even if it is deeply nested in node modules dependencies.
More info about `globally override require`:
https://github.com/thlorenz/proxyquire#globally-override-require
=> COMPASS-3589 testing srv

lib/connection-collection.js, lib/extended-model.js, test/ssh-tunnel.test.js
- Update accessing app name from remote electron app
- Update the property name. Replace wrong `appname` with proper `appName`
Part of: https://jira.mongodb.org/browse/COMPASS-3821
=> fix: set proper app name

lib/extended-model.js
**Description**
Server log should include application metadata:
```
2019-09-10T10:23:11.168+0200 I NETWORK  [conn21] received client metadata from
127.0.0.1:57822 conn: {
driver: { name: "nodejs-core", version: "3.2.7" },
os: { type: "Darwin", name: "darwin", architecture: "x64", version: "18.6.0" },
platform: "Node.js v10.2.0, LE",
application: { name: "MongoDB Compass Dev" }
}
```
**Checklist**
**Types of changes**
=> COMPASS-3887 Make sure server appname is properly set

lib/model.js
**Description**
Increase ssh tunnel connection timeouts from 5 seconds to 20 seconds	
**Checklist**
**Types of changes**
=> COMPASS-723 Increase ssh tunnel connection timeouts

lib/model.js
Update a connection model to be able to unset all properties. Only `uuidRepresentation` and `compression` were throwing the error because ampersand js didn't allow to use `undefined` as value of `uuidRepresentation`. And failed to parse `this.compression.compressors` when `compression` had `undefined` value.
=> fix: allow to unser properties

lib/model.js, test/build-uri.test.js
Since x509Username can include special characters such as `:` we should use percent-encoding to distinguish a delimiter from the part of the username component. Otherwise a part of the username that follows `:`  will be parsed by the driver as a password. And the password is not allowed for the `MONGODB-X509` mechanism.
Fixes [COMPASS-4104](https://jira.mongodb.org/browse/COMPASS-4104)
=> fix(x509): COMPASS-4104: urlencode credentials when using X509 auth

lib/model.js, test/build-uri.test.js, test/connect.test.js
COMPASS-4057
The generated driver URI cannot connect via a SSH tunnel because the current behaviour replaces the host and port of the cluster with the actual SSH tunnel details.
=> COMPASS-4057: Don't replace host/port on SSH tunnel connect

package-lock.json, package.json
vscode can't support native addon's yet so including the Kerberos dependency causes the `Module did not self-register` error message. Since Compass includes Kerberos as a hard dependency already and the node driver uses a conditional require, this should be a noop which unblocks vscode.
=> chore: VSCODE-81 remove extraneous kerberos native add on dep

.eslintrc, lib/connect.js, lib/model.js, test/connect.test.js
Initially, when we had only one view on the connect screen, and connections string was copied from the clipboard to fill in a connection form only once in background, our connection model was parsing URI and in case of ssh connection replaced hostname and password with ssh address and port.
Later with the connection v2 we introduced the possibility to edit connection strings and parse them to connection form attributes and vise versa. Because of this, the ssh injection stated happening not at the very last moment, but each time when we were switching views. You could see it when filling in ssh data on the connect form view and then switching to the URI view. The ssh port was replacing the 27017 value in URI.
It introduced the following issue with favorites: …
=> COMPASS-4268: Use proper password for ssh

lib/model.js, test/parse-and-build-uri.js
https://jira.mongodb.org/browse/COMPASS-4278
This PR changes how we build the query string's `readPreferenceTags` to ensure we keep tag groups intact and don't lose tag data. 
https://docs.mongodb.com/manual/core/read-preference-tags/
Tested locally with replica set - previous compass wouldn't connect, now it can connect. Tested with multiple read preference tag sets.
Testing steps:
```
1. Start up local replica set:
mongod --replSet rs1 --port 27017 --dbpath=/users/Rhys/data/rs-1-0 --bind_ip localhost --oplogSize 128
mongod --replSet rs1 --port 27018 --dbpath=/users/Rhys/data/rs-1-1 --bind_ip localhost --oplogSize 128
mongod --replSet rs1 --port 27019 --dbpath=/users/Rhys/data/rs-1-2 --bind_ip localhost --oplogSize 128
2. Set up the local replica set and give tags to different nodes. …
```
=> COMPASS-4278: Read preference tag group to url fix

package-lock.json, package.json
Looks like the dependency update just updated `package-lock.json` not `package.json` https://github.com/mongodb-js/connection-model/commit/82e94136a2e7269abc3127d4dc735303c0a29103?branch=82e94136a2e7269abc3127d4dc735303c0a29103&diff=split
=> Bump storage mixin to 3.3.4

lib/model.js, test/parse-uri-common-targets.test.js
Internal use of `async/await` and promises in `Connection.from` to simplify the code and properly deal with the asynchronous parsing in case of errors. 
NOTE: we are also dropping the "normalisation" of the scheme (adding the scheme if not present). Since the url scheme is validated in `compass-connect` that feature is never used, also not behaving properly:
```
http://my-host --> mongodb://http://my-host
```
```
bad-protocol://somehost?#mongodb+srv:// --> bad-protocol://somehost?#mongodb+srv://
```
To be precise this should probably be a new major version.
=> fix: safe async parsing of connection strings

lib/model.js, test/build-uri.test.js, test/parse-uri-common-targets.test.js
This updates our connection model to not require an auth username when the `authMechanism` is set to `MONGODB-X509` and we are building a connection string, or parsing a connection string.
This PR also updates parsing a URL to remove the clause where we would assume the auth mechanism is `MONGODB-X509` when just auth username was set.
This fixes an issue where we build an incorrect connection string in vscode, where x509 username is optional.
=> fix(VSCODE-202): Allow x509 username to be optional in connection string parsing and building

lib/ssh-tunnel.js
When a keyfile with passphrase was selected for SSH Tunnel authentication and the passphrase is empty/invalid _no error message was displayed_ previously. The error is now caught and properly forwarded.
=> fix: Ensure error thrown on connect is forwarded COMPASS-4473

lib/model.js, test/build-uri.test.js
We'll also want to update `compass-connect` so that the validation error when x509 is selected is shown properly. Right now it's not showing the actual validation errors, is just says `The required fields can not be empty` and highlights the x509 input.
=> fix: don't require username with x509 auth

lib/connect.js, test/connect.test.js
This PR exposes connection options that are passed to the `MongoClient` to establish a connection in a connect done callback.
Even though `driverOptions` and `driverUrl` are exposed on the connection model, they are not exactly the same options that are passed to the `MongoClient` when connecting to the server. To allow replication and reuse of the exact connections created by the connect.
In our particular case in scope of moving the mongo shell in compass in a separate thread we would need to replicate the connection in a thread with shell runtime and for this having an easy access to the exact options used by `MongoClient` will be very handy.
–
–
This is a minor change unless there are concerns about having a third argument in a done callback, which is not a very common pattern in …
=> feat(COMPASS-4517): Expose connection options

lib/connect.js
In the connection string we use the driver to resolve the replica set name, so the `directConnection` option was not being set there. However, in the connection form we do not resolve the replica set name before connecting, so it was blank and therefor we were setting directConnection to true when it was an srv record, since there's only one host and no replica set. This PR updates it so that we check if it's an srvRecord so we don't set `directConnection` true on those connection.
=> fix: when isSrvRecord is true do not default directConnection to true in driver connection options

lib/data-types.js, lib/model.js, test/ssh-tunnel.test.js
This brings back the `port` data type removed by #341. Pinning the port data type to `number` would cause Compass to fail loading stored favorites.
=> fix: bring back 'port' data type

README.md, constants/auth-strategy-to-field-names.js, lib/model.js, package-lock.json, package.json, test/build-uri.test.js, test/model.test.js, test/parse-and-build-uri.js, test/parse-uri-common-targets.test.js
Removes the Kerberos password field from the connection model.
Also bumps `mongodb-runner` to the latest version to make it work on Node 14.x.
=> chore: remove kerberos password COMPASS-4378

lib/extended-model.js, test/model.test.js
This PR updates so that the model has the correct title on connections created with the connection form (host and port aren't set).
before:
https://user-images.githubusercontent.com/1791149/107398392-dc4a6580-6aff-11eb-906b-701d5bb7d4d0.mp4
after:
https://user-images.githubusercontent.com/1791149/107397687-2d0d8e80-6aff-11eb-9685-f07bd96984b8.mp4
=> fix: incorrect connection title on form connections

lib/extended-model.js
Fixes the title of connections so we don't cache them. This was causing the title not to change when a user updated the port.
=> fix: don't cache title and use port as title dep
