mongodb-js/connection-model

.jsfmtrc
.travis.yml
README.md
index.js
package.json
test/index.test.js

still need to sweep back for better SSL and updating SSL tests but looking for feedback from @kangas and @judahschvimer on this refactoring to make this all more human.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb-js/mongodb-connection-model/2)

:construction: refactoring

---

.travis.yml
lib/model.js
package.json
test/connect.test.js
test/index.test.js

also :arrow_up: mongodb-url@1.0.2

:bug: fix auth source

---

lib/model.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/59)

INT-1308: Use read preference secondary preferred

---

lib/model.js
test/index.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/69)

INT-1408: Add SSH Tunnel Options & Validation

---

README.md
lib/connect.js
lib/ssh-tunnel.js
test/connect.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/88)

Examples, Docs, and API improvements for SSH Tunnel and status events

---

package.json

cc/ @imlucas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/89)

INT-1540: Bump kerberos, make dependencies

---

browser.js
package.json

closes #100, closes #101, closes #102, closes #103.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/104)

:shirt: bumped eslint-config and fixed lint error

---

lib/model.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/107)

INT-1763: Add promote_values attribute to model

---

lib/model.js
test/index.test.js

Compass 86 Atlas UX

---

README.md
lib/model.js
test/index.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/connection-model/113)

INT 1709: SYSTEMCA

---

package.json

Found by trying out npm-check:
https://github.com/dylang/npm-check
Just putting this up to see if it passes CI while I look more deeply to see when it was actually presumably used in the past.

Remove mongodb-ns

---

package.json

Should just be a couple of bug fixes:
https://github.com/mscdex/ssh2/compare/b62b5430ebde1bb135297e08426cd073abc684da...18859cc50e03c2e12738a323470c3e5ddd6b66f5

:arrow_up: ssh2@0.5.4

---

package.json

https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#320--2016-11-24

:arrow_up: mocha@3.2.0

---

.travis.yml
package.json

chore(package): update async to version 2.1.5 
https://greenkeeper.io/
#retry AWS S3 down fallout

:arrow_up: async@2.1.5

---

.travis.yml

Turn node_modules / npm cache back on

---

lib/model.js

This PR abstracts the `this.authentication` switch of `if` and `else if` statements into an `encodeAuthForUrlFormat` arrow function, which will avoid triggering a new complexity warning in a future PR.

Refactor: Reduce complexity

---

lib/connect.js
lib/model.js

Srv connection string can have only one hostname

COMPASS-3589 SRV connection string fix

---

lib/model.js

Trailing comma removed

---

lib/connect.js
lib/connection-collection.js
lib/extended-model.js
lib/model.js

Add connection color property.

COMPASS-3618 add connection color property

---

lib/extended-model.js
lib/model.js

Remove extra props from model and store color as a string.

COMPASS-3618 clean up

---

README.md

docs: remove name from readme

---

lib/model.js
test/build-uri.test.js

I have noticed that one of `Connection.from` wasn't converted to async call. Fixed it.

COMPASS-3971 connection from must be async

---

lib/model.js

Refactor model to remove empty compression from a defauld URI.

COMPASS-3971 clean uri from an empty compression

---

package-lock.json
package.json
test/connect.test.js

COMPASS-3991 Update to node driver 3.3.5

---

lib/model.js
test/build-uri.test.js

Set default kerberosServiceName instead of doing it in the `compass-connect` plugin.
Remove from `compass-connect`:
```
_updateDefaults() {
const connection = this.state.currentConnection;
if (
(connection.authStrategy === 'MONGODB' ||
connection.authStrategy === 'SCRAM-SHA-256') &&
isEmpty(connection.mongodbDatabaseName)
) {
connection.mongodbDatabaseName = 'admin';
} else if (
connection.authStrategy === 'KERBEROS' &&
isEmpty(connection.kerberosServiceName)
) {
connection.kerberosServiceName = 'mongodb';
}
},
```
The same logic is implemented here in `connection-model`:
https://github.com/mongodb-js/connection-model/blob/0b16cf1186e8690a734f62e77a763ad00ab92ee5/lib/model.js#L465-L479
Dependency of: https://github.com/mongodb-js/compass-connect/pull/141

COMPASS-4089: set default kerberosServiceName

---

README.md
lib/model.js
test/build-uri.test.js

Along with `driverUrl` that is being used to connect build `safeUrl` for UI where a password is replaced with stars.

feat: build safeUrl

---

README.md
lib/connect.js
lib/connection-collection.js
lib/extended-model.js
lib/model.js
package-lock.json
package.json

Thinking about other projects that use the connection model and do not use data service for connecting, we can expose the driver URL with ssh tunnel port injected instead of injecting it at the very last moment before connecting.
To keep the same amount of exposed URLs I removed `baseUrl` that was used only internally in connection model to build `safeUrl` and `driverUrl`. I use the `prepareRequest()` function instead, that exists outside the Ampersand model and the result of which is being consumed by `safeUrl`, `driverUrl` and new `driverUrlWithSsh`.
For ssh connections `driverUrlWithSsh` will return driverUrl with ssh port injected. For regular connection, the driverUrlWithSsh will return regular `driverUrl`. So it is safe to connect with driverUrlWithSsh for any types of connections …

VSCODE-122: Playground through SSH connection

---

package-lock.json
package.json

Compass uses `electron@6.1.7` as a dependency. All plugins should use the same version to be consistent.

Build: Use electron 6

---

lib/model.js
test/build-uri.test.js
test/ssh-tunnel.test.js

When building `driverUrlWithSsh` use a real auth instead of safe password.

Fix: Use a real password for driver url with ssh

---

.eslintrc
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.vscode/settings.json
lib/connect.js
lib/connection-collection.js
lib/extended-model.js
lib/local-port-generator.js
lib/model.js
lib/ssh-tunnel.js
package-lock.json
package.json
test/build-uri.test.js
test/connect.test.js
test/model.test.js
test/parse-and-build-uri.js
test/parse-uri-common-targets.test.js
test/parse-uri-components.test.js
test/ssh-tunnel.test.js

I started this branch for investigating COMPARR-4315 when user gets a white screen when selecting a favorite or switching between the form views. Unfortunately, I couldn't reproduce this behavior. But I did a refactoring and:
- Removed extra parsing of URL that potentially could throw an error and use a new `srvHost` property that was added by the Node driver to the parsed object.
- Added `try-catch` blocks around `decodeURIComponent` that can potentially throw an URIError ("malformed URI sequence") exception when used wrongly.
- Bumped versions of dependencies including fixes in Node driver to improve the connect experience.
- Added vscode config to automatically prettify code, because I found it was very useful during the development of vscode extension. It keeps the code style …

COMPARR-4315: refactoring and srvHost

---

lib/model.js
test/parse-uri-components.test.js

Add a try/catch in `Connection.from` that avoid some exceptions to evade the `Connection.from` callback and result in unhandled exception crashing compass.
- To be really safe we should wrap in a try/catch the whole `Connection.from`, is not related to this ticket, however probably would be a good thing to do.
-  Those issues could be avoided all together by using Promises and async/await. Is the reason for using callbacks still valid, or we could switch, at least internally?

COMPASS-4380: handle ampersand validation errors

---

lib/model.js
test/parse-and-build-uri.js

Fixes https://jira.mongodb.org/browse/COMPASS-4430

fix: cannot connect with SCRAM-SHA-256 from connection url

---

lib/model.js
test/build-uri.test.js
test/parse-uri-common-targets.test.js

To be more stringent in adhering to RFC 3986, replace !, ', (, ), and * with a corresponding character code.
Related issue: https://github.com/mongodb-js/vscode/issues/169

VSCODE-198: use RFC 3986 encoding

---

package-lock.json
package.json

deps: move mongodb to peer deps and dev deps
